language: ruby

rvm: 2.3.3

cache: bundler

sudo: false

env:
  global:
  - secure: sI+V7aDQuIxritVCR8okVzQ4N2NZr5MuXO31IcIZEnVmnEnfc72pG5HPfOt6jwAV8mja6lfJD4W8/VAoGxdsvVrdPTB4IITKYNiSwlw/heIsT4lkfof7zC33+kzFw2P1KKVBKEiEu12H6uPpBtT1oGWoewoPz2OKrs+IdgdcOfGWRBpZ1CC16TP8Q4WcvubqIYNbfbnijLmpv5G+NXOxTqTUae//q5WehEeIUfAGCLfxXJ9pZZFqVffhofc++5/N57zIVbQmcnplcBsURs7/K1EoTGAApekt/BiMhnoIGf2YhKaAwZWhkNZ8XjvtgMlACxrMU5jFT5B517p99BBJEcirxPQ0ZAU82GPGLUQrh9+VfGEQ8BA2txiePm0mP1iHhu5W05E0uWqfzrKm+YZkA94IGQfns3qLWM7JYrxkmKXL3UArL+o71zLdct9uYwtuHBjAmERvmvvH36zPINfFLC4Gfw7ayX5+mhAy2ooyS/i0NxrSiEILXDbOu9hmao0UfW1WlOoAitqv3yDfqcZp981VSHg+5VR4A50tQ7Qra1jHdLMR9GYl7KAznPm6zflIplomX+cEwi9XSjE19DwbEUwdQz0JlR79JAgDkNJA+gcQtizZF8GDGeXNtBsWTz2RrCwc2vYp7iwGkDMeHAuHGg6UhLeNz1RaLcAGE9vKt5Q=

notifications:
  email: false

branches:
  only:
  - master

before_script:
  - chmod +x ./build.sh
  - chmod +x ./deploy.sh

script: ./build.sh

after_success: ./deploy.sh